name: Build

on: push

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repo
        uses: actions/checkout@v2
      - name: Build with make
        run: make all
